### ISSUE TITLE
SphinxQL syntax error in __search

### ISSUE THREAD

**Issue by netfl0** [smartfile/django-sphinx-db#1]
```
q = EntryIndex.objects.filter(content__search='title')

In [42]:      q.model
Out[42]:    nfeeder.models.EntryIndex

In [43]: print q.query
SELECT `nfeeder_entryindex`.`id`, `nfeeder_entryindex`.`content`, `nfeeder_entryindex`.`date` 
FROM `nfeeder_entryindex` WHERE MATCH (`nfeeder_entryindex`.`content`) AGAINST
 (title IN BOOLEAN MODE);
```

I am trying to search the index with the orm. It works fine from the mysql command line with:

```
select * from nfeeder_entryindex where MATCH('title');
```

I am not sure if I am doing something wrong.

**Comment by btimby** [comment]
Peter,

The ORM search SQL syntax looks like the MySQL variant instead of the Sphinx version. It may be that your model is not using the SphinxManager `objects = SphinxManager()`.

**Comment by netfl0** [comment]
Ben,

I tried to match the example in your Readme, I added the objects assignment
as you suggested:

```
class EntryIndex(SphinxModel):
    class Meta:
        # This next bit is important, you don't want Django to manage
        # the table for this model.
        managed = False

    objects = SphinxManager()
    content = SphinxField()
    date = models.DateField()
```

This appears to be working, I guess I had assumed inheriting the
SphinxModel would have done that for me. Thanks for the help!

On Mon, Apr 2, 2012 at 09:45, Ben Timby <
reply@reply.github.com

> wrote:
> 
> Peter,
> 
> The ORM search SQL syntax looks like the MySQL variant instead of the
> Sphinx version. It may be that your model is not using the SphinxManager
> `objects = SphinxManager()`.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/btimby/django-sphinx-db/issues/1#issuecomment-4878634

## 

-Pete

**Comment by btimby** [comment]
https://github.com/btimby/django-sphinx-db/commit/25e8af9c69dd31f23db654770aef91d36772b626

The manager is now defined on the SphinxModel class. Because this model is abstract, the manager should now be inherited by subclasses.

You will no longer need to manually define the manager for SphinxModel subclasses. The related Django documentation is here:

https://docs.djangoproject.com/en/dev/topics/db/managers/#custom-managers-and-model-inheritance
